name: businesstravel
description: A new Flutter project.

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  json_annotation: ^0.2.4
  local_auth: "^0.2.1"
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: '^0.1.2'  
  #shared_preferences: '^0.4.2'
  url_launcher: '^4.0.1'
  http: "^0.11.3+16"
  
dev_dependencies:
  build_runner: ^0.9.2
  json_serializable: ^0.5.0

  flutter_test:
    sdk: flutter
    

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/background.jpg
    - assets/AA_logo.png
    - assets/United_logo.png
    - assets/Delta_logo.png
    - assets/Burberry_Offer.JPG
    - assets/Forbes_Offer.jpg
    - assets/MontBlanc_Offer.jpg
    - assets/Starbucks_Offer.jpg
    - assets/Event_1.jpg
    - assets/Event_2.jpg
    - assets/Event_3.jpg
    - assets/Event_4.jpg
    - assets/Upsell.jpg
    - assets/HotelUpgrade.jpg
    - assets/RentImage.png
    - assets/HotelBooking.jpg
    - assets/carbooking.jpg
    - assets/hotel_hilton.jpg
    - assets/hotel_MandarinOriental.jpg
    - assets/hotel_sofitel.jpg
    - assets/hotel_WillardInterContinental.jpg
    - assets/Avis_logo.jpg
    - assets/Budget_logo.png
    - assets/Enterprise_logo.jpg
    - assets/Hertz_logo.png
    - assets/SmallCar.jpg
    - assets/IntermediateCar.jpg
    - assets/FullSizeCar.jpg
    - assets/SUVCar.jpg
    - assets/qr_code.png
    - assets/washingtonmonument.jpg
    - assets/event-icon-dsbr.png
    - assets/eents.png
    - assets/airporttile.png
    - assets/Wine&Dine.gif
    - assets/Locale.png
    - assets/Events.jpg
    - assets/Weather.gif
    - assets/MyDeals.jpg
    - assets/cross-sell-upsell.png
    - assets/attractions.jpg
    - assets/chat.jpg
    - assets/United_Airlines_Logo.jpg
    - assets/hilton.png
    - assets/HubBG.png
    - assets/budget.png
    - assets/uber.jpg
    - assets/travelhub_black.png
    - assets/black-background.jpg
    - assets/1logo_cbt.png
    - assets/2logo_cbt.png
    - assets/imgevent1.jpg
    - assets/imgevent2.jpg
    - assets/imgevent3.jpg
    - assets/Weather.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
fonts:
  - family: Whitney
    fonts:
      - asset: fonts/3955045D2CF71A4B6.woff2
      - asset: fonts/2AEF2F564D90434B1.woff2
        style: italic